[package]
name = "chip8_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = { version = "0.9.2" }

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
getrandom = { version = "0.3", features = ["wasm_js"] }