[package]
name = "sdl_emu"
version = "0.1.0"
edition = "2024"


[dependencies]
sdl2 = { version = "0.38.0", features = ["bundled"] }
rfd = { version = "0.17.2"}
chip8_lib = { path = "../../chip8_lib" }